# Generated by Django 4.1 on 2023-12-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('rank', models.IntegerField(verbose_name='等级')),
                ('blood', models.IntegerField(verbose_name='血量')),
                ('money', models.IntegerField(default=0, verbose_name='金币')),
            ],
        ),
    ]
