# Generated by Django 4.1 on 2023-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='任务名称')),
                ('type', models.IntegerField(verbose_name='任务类型')),
                ('begin', models.DateField(verbose_name='开始日期')),
                ('end', models.DateField(verbose_name='结束日期')),
                ('frequency', models.IntegerField(verbose_name='频率')),
            ],
        ),
        migrations.CreateModel(
            name='DateTodoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('tasks_todo', models.ManyToManyField(to='TestModel.taskinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DateCheckInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('tasks_done', models.ManyToManyField(to='TestModel.taskinfo')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tasks',
            field=models.ManyToManyField(to='TestModel.taskinfo'),
        ),
    ]
