# Generated by Django 4.1 on 2023-12-14 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_taskinfo_datetodoinfo_datecheckinfo_userinfo_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfo',
            name='begin',
            field=models.DateField(default=datetime.date(2023, 12, 14), verbose_name='开始日期'),
        ),
    ]
