# Generated by Django 4.1 on 2023-12-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_alter_taskinfo_begin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('attack_power', models.IntegerField()),
                ('defense_power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='attack_power',
            field=models.IntegerField(default=0, verbose_name='攻击值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='defense_power',
            field=models.IntegerField(default=0, verbose_name='防御值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='experience',
            field=models.IntegerField(default=100, verbose_name='经验值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='equipements',
            field=models.ManyToManyField(to='TestModel.equipmentinfo'),
        ),
    ]
