# Generated by Django 4.1 on 2023-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_equipmentinfo_userinfo_attack_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecheckinfo',
            name='date',
            field=models.DateField(unique=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='datecheckinfo',
            name='tasks_done',
            field=models.ManyToManyField(related_name='已经打卡的任务', to='TestModel.taskinfo'),
        ),
        migrations.AlterField(
            model_name='datetodoinfo',
            name='date',
            field=models.DateField(unique=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='datetodoinfo',
            name='tasks_todo',
            field=models.ManyToManyField(related_name='需要做的任务', to='TestModel.taskinfo'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='attack_power',
            field=models.IntegerField(verbose_name='攻击值'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='defense_power',
            field=models.IntegerField(verbose_name='防御值'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='level',
            field=models.IntegerField(verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='装备名称'),
        ),
        migrations.AlterField(
            model_name='equipmentinfo',
            name='type',
            field=models.IntegerField(verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='equipements',
            field=models.ManyToManyField(related_name='设备', to='TestModel.equipmentinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tasks',
            field=models.ManyToManyField(related_name='任务', to='TestModel.taskinfo'),
        ),
    ]
