# Generated by Django 4.1 on 2023-12-20 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_alter_datecheckinfo_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='待办事项名称')),
                ('date', models.DateField(default=datetime.date(2023, 12, 20), verbose_name='开始日期')),
                ('state', models.IntegerField(verbose_name='完成情况')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskinfo',
            name='type',
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='begin',
            field=models.DateField(default=datetime.date(2023, 12, 20), verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='todos',
            field=models.ManyToManyField(related_name='待办', to='TestModel.todoinfo'),
        ),
    ]
