# Generated by Django 4.1 on 2023-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_todoinfo_remove_taskinfo_type_alter_taskinfo_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetodoinfo',
            name='todos',
            field=models.ManyToManyField(related_name='待办事项', to='TestModel.todoinfo'),
        ),
        migrations.AlterField(
            model_name='datetodoinfo',
            name='tasks_todo',
            field=models.ManyToManyField(related_name='每日任务', to='TestModel.taskinfo'),
        ),
    ]
