# Generated by Django 4.1 on 2023-12-22 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_datetodoinfo_todos_alter_datetodoinfo_tasks_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinfo',
            name='value',
            field=models.IntegerField(default=20, verbose_name='价值'),
        ),
        migrations.AlterField(
            model_name='datetodoinfo',
            name='tasks_todo',
            field=models.ManyToManyField(blank=True, related_name='每日任务', to='TestModel.taskinfo'),
        ),
        migrations.AlterField(
            model_name='datetodoinfo',
            name='todos',
            field=models.ManyToManyField(blank=True, related_name='待办事项', to='TestModel.todoinfo'),
        ),
        migrations.AlterField(
            model_name='taskinfo',
            name='begin',
            field=models.DateField(default=datetime.date(2023, 12, 22), verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='todoinfo',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 22), verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='attack_power',
            field=models.IntegerField(default=0, verbose_name='攻击值'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='blood',
            field=models.IntegerField(default=100, verbose_name='血量'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='defense_power',
            field=models.IntegerField(default=0, verbose_name='防御值'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='equipements',
            field=models.ManyToManyField(blank=True, related_name='设备', to='TestModel.equipmentinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='任务', to='TestModel.taskinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='todos',
            field=models.ManyToManyField(blank=True, related_name='待办', to='TestModel.todoinfo'),
        ),
    ]
